public class TriggersOverview {
	
    // syntax
    // trigger TriggerName on ObjectName(trigger_events) {
    // //code-block 
    // }

    //extension of trigger is .apxt

        // trigger events
    // Before insert
    // Before update
    // Before delete
    // After insert
    // After update
    // After delete
    // After undelete
    // 
    //      Code Examples
    //      
    //Before insert  =>  UppercaseAccountName
    //before update  => beforeUpdateExample
    //after insert   =>  afterInsertExample
    
    
    // Context variables
    // 
    // trigger.new =>  newContextVariable
    // trigger.old => oldContextVariable
}